[MARVP-5] Integrate Linkedin Login
mishradileep/accelerate-2019 pull request #1
Opened 2019-07-30 06:58 UTC by vijaysamanthapudi

2019-07-30 10:56 UTC, krishk95 commented on KonyAccelerate/controllers/mobile/frmLoginController/frmLoginControllerActions.js
>          alert("login failed");
Please remove the alerts

2019-07-30 10:57 UTC, krishk95 approved these changes

2019-07-30 11:26 UTC, mishradileep requested changes
Do we need to push all the variants of Karbon fonts ? Please remove which are not in use

2019-07-31 05:45 UTC, vigneshwarankarunanithi commented on KonyAccelerate/userwidgets/com.konymp.linkedinlogin/userwidgetmodel.sm/flxMain.json
> +    "_skin_": "s90dae5418f546c9bbfde0ff0a290743",
Remove the blue border.

2019-07-31 06:12 UTC, vigneshwarankarunanithi reviewed
1. Fix Browser widget height issue (run time)

2019-07-31 07:19 UTC, vijaysamanthapudi commented on KonyAccelerate/controllers/mobile/frmLoginController/frmLoginControllerActions.js
>          alert("login failed");
Alert Removed

2019-07-31 07:20 UTC, vijaysamanthapudi commented on KonyAccelerate/userwidgets/com.konymp.linkedinlogin/userwidgetmodel.sm/flxMain.json
> +    "_skin_": "s90dae5418f546c9bbfde0ff0a290743",
Border Removed

2019-07-31 07:27 UTC, merged