[feature/MARVP-42] event feedback animation
mishradileep/accelerate-2019 pull request #23
Opened 2019-08-05 12:24 UTC by krishk95

2019-08-05 12:35 UTC, mishradileep requested changes
Need some serious attention on code formatting/indentation. Also, check comments inline

2019-08-05 12:35 UTC, mishradileep commented on actions/mobile/appEvents.js
> +            "data": "Sample Test"
Can we put some meaningful text here. Get Siddhanta's help if required.

2019-08-05 12:35 UTC, mishradileep commented on controllers/mobile/frmFeedbackController/frmFeedbackController.js
> +        this.animateFeedbackPrompt("100dp", false);
A function doing nothing but calling another function. Can we remove this

2019-08-05 12:35 UTC, mishradileep commented on controllers/mobile/frmFeedbackController/frmFeedbackController.js
> +        this.animateSubmitButton("100%", true);
Same as above

2019-08-06 04:20 UTC, vigneshwarankarunanithi approved these changes

2019-08-06 11:23 UTC, vijaysamanthapudi approved these changes

2019-08-06 11:29 UTC, merged